### ISSUE TITLE
MVPレビュー

### ISSUE THREAD

**Issue by Tsuchiya2** [navybook/EmoBridge#38]
MVPリリースお疲れ様でした。
挙動に問題ないことが確認できました。LGTMです。
以下により良くするためのレビューを記載します。
レビュー内容をタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに修正完了までのスケジュール・本番リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

---

■LIFF
・LINE上からでも投稿ができたりすると、手軽さが増してユーザー体験がよくなるかと思いました。

■独自ドメイン
・独自ドメインを取得して反映させましょう。

■お問い合わせ
・既にisseu化されていたので、そちらも進めましょう。

■OGP
・XにURLを載せた際にOGPが表示されるようにすると、拡散の促進になるかと思いますので行いましょう。（細かい部分もケアできる印象を与える要素にも繋がるかと思います）

■RSpec
・RSpecを用いてモデルテスト・システムテスト・リクエストテストを書きましょう。（リクエストテストは本リリース後で大丈夫です）

■CI（GitHubAction）
・GitHubActionを使ってRSpec・Rubocopが行われるようにしましょう。（イメージ：プルリクエストやプッシュなどがされたタイミングでCIが動いてRSpec・Rubocopが走って検証が行われる感じです）

■オートログイン
・ユーザー登録時にオートログインされるようにしましょう。ユーザー体験の向上に繋がるかと思います。

■LINE送信時にアニメーション（思いつきのアイディアです）
・投稿時にパートナーに向けて投稿したものが送られているアニメーションが入ると、相手に送信している感が演出されて、ユーザー体験を向上できるかと思いました。

**Comment by navybook** [comment]
@Tsuchiya2 

いつもお世話になってます。
上記について回答が遅くなり大変申し訳ありません。

上記の対応スケジュールとしては、6/15予定として、その後、本番リリースまでは、6/22目標としたいと思ってます。
よろしくお願いします。
